### ISSUE TITLE
Need a better way of detecting the Perl version to check

### ISSUE THREAD

**Issue by steve-m-hay** [rjbs/Test-MinimumVersion#9]
I do not have META.yml / META.json files in my Git repo since they are generated files, so all_minimum_version_from_metayml_ok() always skips, forcing me to use a hard-coded version number instead, e.g.:

https://github.com/steve-m-hay/Text-Balanced/commit/d1000a6a0b

Would an all_minimum_version_from_mymetayml_ok() function be a good idea? Or maybe default to using MYMETA.yml in all_minimum_version_from_metayml_ok() if MYMETA.yml exists and META.yml doesn't?

Alternatively, could the Perl version to check be found from within each Perl file itself? They all have "use 5.008001;" in them after all.

**Comment by rjbs** [comment]
The risk with having it use mymeta without the author's consent is that the perl version may change dynamically from what is advertised in META.yml.  This is a bit of an edge case, but I think it's probably worth respecting, especially since it should be pretty easy to just add a _mymeta_ version that looks for a MYMETA file.

I'll merge a PR that does this.

**Comment by steve-m-hay** [comment]
Thanks. See https://github.com/rjbs/Test-MinimumVersion/pull/10

**Comment by rjbs** [comment]
Thanks, merged and released!
